version: 2
project_name: linkquisition

builds:
  - id: "application"
    binary: "linkquisition"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=clang
    main: ./cmd/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "unwrap-plugin"
    binary: "plugins/unwrap.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/unwrap/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "terminus-plugin"
    binary: "plugins/terminus.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/terminus/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

sboms:
  - artifacts: archive
