name: CI

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libgtk-4-dev libglib2.0-dev libgirepository1.0-dev
      - uses: anchore/sbom-action/download-syft@v0
      - name: Install Task
        uses: go-task/setup-task@v1
      - name: Run Tests
        run: task test

      - name: Package files for Linux
        run: task package:linux

      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
          hooks: goreleaser
        env:
          # GITHUB_TOKEN -env is required for the goreleaser -hook
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
