name: pull-request
on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libgtk-4-dev libglib2.0-dev libgirepository1.0-dev libgirepository1.0-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=10m

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libgtk-4-dev libglib2.0-dev libgirepository1.0-dev
      - name: Install Task
        uses: go-task/setup-task@v1
      - name: Run Tests
        run: task test

  build:
    name: build the application and plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libgtk-4-dev libglib2.0-dev libgirepository1.0-dev

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Build main application
        run: task build:linux-amd64

      - name: Build plugins
        run: task build:plugins
